import * as T from 'three';
import {routeMap} from './route-map';
import {obstacleCeiling} from './terrain';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {FlightController,labels,Frame,routes,FlightCommand} from './flight';import {environment} from './environment';import './style.css';
const $=<E extends HTMLElement>(s:string)=>document.querySelector<E>(s)!;
const canvas=$<HTMLCanvasElement>('#scene');
const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color(0xa4becb);scene.fog=new T.Fog(0xa4becb,650,3200);
const camera=new T.PerspectiveCamera(42,1,.1,5000);camera.position.set(8,3.6,10);
const controls=new OrbitControls(camera,canvas);controls.target.set(0,.65,0);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=3000;controls.maxPolarAngle=Math.PI*.49;controls.update();
scene.add(new T.HemisphereLight(0xd6e9ff,0x58624a,1.3));const sun=new T.DirectionalLight(0xffefd4,2.4);sun.position.set(-35,65,25);sun.castShadow=true;Object.assign(sun.shadow.camera,{left:-15,right:15,top:15,bottom:-15,near:1,far:150});sun.shadow.bias=-.0002;sun.shadow.normalBias=.02;scene.add(sun,sun.target);
const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),envmap=pmrem.fromScene(room,.025);scene.environment=envmap.texture;scene.environmentIntensity=.45;room.dispose();pmrem.dispose();
const terrain=environment(scene),aircraft=new T.Group();aircraft.name='Flight_Pose';scene.add(aircraft);
let flight:FlightController,ready=false,cameraMode='free',showLabels=false;
type Rotor={pivot:T.Object3D;base:T.Quaternion;parts:T.Material[];disc:T.Mesh<T.CircleGeometry,T.MeshBasicMaterial>;lift:boolean;sign:number};
const rotors:Rotor[]=[],axis=new T.Vector3(0,1,0),spin=new T.Quaternion();
const labelData=[{name:'宽体货舱',pos:new T.Vector3(0,.75,1.15)},{name:'8 旋翼 · 共轴升力',pos:new T.Vector3(-1.24,1,.94)},{name:'7 m 复材主翼',pos:new T.Vector3(2.7,.96,0)},{name:'巡航尾推',pos:new T.Vector3(0,.92,-1.8)}];
const routeSelect=document.createElement('select');routeSelect.id='route';routeSelect.setAttribute('aria-label','飞行航线');for(const [id,r] of Object.entries(routes)){const o=document.createElement('option');o.value=id;o.textContent=r.name;routeSelect.append(o);}const routeLabel=document.createElement('label');routeLabel.className='field';routeLabel.textContent='飞行航线';routeLabel.prepend(routeSelect);$('.right-tools')?.prepend(routeLabel);
const mapWrap=document.createElement('div');mapWrap.className='route-map';mapWrap.innerHTML='<span>航线 / 完成度 <b id="route-progress">0%</b></span><canvas width="180" height="92" aria-label="飞行航线缩略图"></canvas>';$('.right-tools')?.append(mapWrap);const mapCanvas=mapWrap.querySelector('canvas')!,missionMap=routeMap(mapCanvas);
for(const d of labelData){const el=document.createElement('div');el.className='part-label';el.textContent=d.name;el.hidden=true;$('#labels').append(el);}const labelEls=Array.from(document.querySelectorAll<HTMLDivElement>('.part-label'));
Promise.all([new GLTFLoader().loadAsync(new URL('ev50.glb',document.baseURI).href),fetch(new URL('flight.json',document.baseURI)).then(r=>{if(!r.ok)throw Error('飞行数据读取失败');return r.json();})]).then(([gltf,data])=>{
 aircraft.add(gltf.scene);flight=new FlightController(data.frames as Frame[]);
 const pivots:T.Object3D[]=[];gltf.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;}if(o.name.startsWith('LiftRotor_')||o.name.startsWith('CruiseRotor_'))pivots.push(o);});
 for(const o of pivots){const isLift=o.name.startsWith('Lift'),mats:T.Material[]=[];
 o.traverse(c=>{if(c instanceof T.Mesh&&/Blade|Tip/.test(c.name)){const copy=(m:T.Material)=>{const n=m.clone();n.transparent=true;mats.push(n);return n;};c.material=Array.isArray(c.material)?c.material.map(copy):copy(c.material);}});
 const disc=new T.Mesh(new T.CircleGeometry(isLift?.58:.25,64),new T.MeshBasicMaterial({color:0x8d979b,transparent:true,opacity:0,side:T.DoubleSide,depthWrite:false}));disc.rotation.x=-Math.PI/2;disc.renderOrder=2;o.add(disc);rotors.push({pivot:o,base:o.quaternion.clone(),parts:mats,disc,lift:isLift,sign:Number(o.userData.spin_sign)||1});}
 if(rotors.filter(r=>r.lift).length!==8||rotors.filter(r=>!r.lift).length!==3)throw Error('动力部件数量校验失败');
 ready=true;flight.evaluate();missionMap.setPath(flight.getPath());$<HTMLInputElement>('#timeline').max=String(flight.duration);$('#loading').hidden=true;$('#load-status').textContent='模型就绪';document.body.dataset.ready='true';for(const el of document.querySelectorAll<HTMLButtonElement|HTMLInputElement>('button,input'))el.disabled=false;$('#summary').textContent='7.00 m 翼展 / 8 + 3 动力系统';
}).catch((e:Error)=>{$('#loading').textContent='加载失败：'+e.message+'。请通过本地服务打开，并检查模型文件。';console.error(e);});
function setMode(mode:'product'|'flight'){if(!ready)return;flight.mode=mode;flight.restart();mapWrap.hidden=mode==='product';flight.playing=mode==='flight';terrain.group.visible=mode==='flight';cameraMode=mode==='flight'?'follow':'free';$<HTMLSelectElement>('#camera').value=cameraMode;controls.enabled=cameraMode==='free';
 if(mode==='product'){camera.position.set(8,3.6,10).multiplyScalar(Math.max(1,1.05/camera.aspect));controls.target.set(0,.65,0);scene.background=new T.Color(0x202c34);scene.fog=null;}else{scene.background=new T.Color(0xa4becb);scene.fog=new T.Fog(0xa4becb,650,3200);}
 $('#product').classList.toggle('active',mode==='product');$('#flight').classList.toggle('active',mode==='flight');$('#mode-label').textContent=mode==='product'?'PRODUCT STUDY':'FLIGHT DEMONSTRATION';$('#play').textContent=flight.playing?'暂停':'播放';$('#timeline-wrap').classList.toggle('muted',mode==='product');}
$('#product').onclick=()=>setMode('product');$('#flight').onclick=()=>setMode('flight');$('#play').onclick=()=>{if(!ready)return;if(flight.mode==='product'){setMode('flight');return;}if(flight.time>=flight.duration)flight.restart();flight.playing=!flight.playing;$('#play').textContent=flight.playing?'暂停':'播放';};$('#restart').onclick=()=>{if(ready)flight.restart();};
$<HTMLInputElement>('#loop').onchange=e=>{if(ready)flight.loop=(e.target as HTMLInputElement).checked;};
$<HTMLInputElement>('#timeline').oninput=e=>{if(!ready)return;const t=Number((e.target as HTMLInputElement).value);if(flight.mode==='product')setMode('flight');flight.seek(t);};
$<HTMLSelectElement>('#camera').onchange=e=>{cameraMode=(e.target as HTMLSelectElement).value;controls.enabled=cameraMode==='free';if(cameraMode==='free'&&ready){controls.target.copy(flight.position);controls.target.y+=.65;controls.update();}};
$<HTMLInputElement>('#annotations').onchange=e=>{showLabels=(e.target as HTMLInputElement).checked;};
routeSelect.onchange=()=>{if(ready){flight.setRoute(routeSelect.value as keyof typeof routes);missionMap.setPath(flight.getPath());}};
const api={command:(c:FlightCommand)=>{if(ready)flight.applyCommand(c);},motor:(lift:number,cruise:number)=>api.command({type:'motor',lift,cruise}),position:(position:number[])=>api.command({type:'position',position}),velocity:(velocity:number[])=>api.command({type:'velocity',velocity}),attitude:(quaternion:number[])=>api.command({type:'attitude',quaternion}),setRoute:(route:keyof typeof routes)=>{routeSelect.value=route;if(ready){flight.setRoute(route);missionMap.setPath(flight.getPath());}},play:()=>{if(ready){flight.clearCommand();if(flight.mode!=='flight')setMode('flight');flight.playing=true;}},pause:()=>{if(ready)flight.playing=false;}};
Object.assign(window,{ev50API:api});window.addEventListener('ev50-command',(e)=>{const c=(e as CustomEvent<FlightCommand>).detail;if(c)api.command(c);});
function quality(q:string){renderer.setPixelRatio(Math.min(devicePixelRatio,q==='Low'?1:q==='Medium'?1.5:2));renderer.shadowMap.enabled=q!=='Low';const size=q==='High'?4096:1024;sun.shadow.mapSize.set(size,size);sun.shadow.map?.dispose();sun.shadow.map=null;terrain.setQuality(q);$('#quality-readout').textContent=q.toUpperCase();resize();}
$<HTMLSelectElement>('#quality').onchange=e=>quality((e.target as HTMLSelectElement).value);
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(cameraMode==='free'){camera.position.set(8,3.6,10).multiplyScalar(Math.max(1,1.05/camera.aspect));if(ready)camera.position.add(flight.position);controls.update();}}window.addEventListener('resize',resize);
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLSelectElement)){e.preventDefault();$('#play').click();}});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#loading').hidden=false;$('#loading').textContent='图形设备连接中断，请刷新页面恢复。';if(ready)flight.playing=false;});
mapWrap.hidden=true;terrain.group.visible=false;scene.background=new T.Color(0x202c34);scene.fog=null;const initialQuality=innerWidth<700?'Low':'High';$<HTMLSelectElement>('#quality').value=initialQuality;quality(initialQuality);
const clock=new T.Clock(),desired=new T.Vector3(),target=new T.Vector3(),v=new T.Vector3();
function animate(){const dt=Math.min(clock.getDelta(),.1);if(ready){flight.tick(document.hidden?0:dt);aircraft.position.copy(flight.position);aircraft.quaternion.copy(flight.quaternion);
 for(const r of rotors){const power=r.lift?flight.lift:flight.cruise,fade=T.MathUtils.smoothstep(power,.06,.30),raw=r.lift?flight.liftAngle:flight.cruiseAngle,angle=(raw%(2*Math.PI))*T.MathUtils.smoothstep(power,0,.08);spin.setFromAxisAngle(axis,angle*r.sign);r.pivot.quaternion.copy(r.base).multiply(spin);for(const m of r.parts)m.opacity=1-fade;r.disc.material.opacity=.16*fade;r.disc.visible=fade>.001;}
 target.copy(flight.position);target.y+=.65;if(cameraMode!=='free'){if(cameraMode==='ground')desired.set(12,2.8,14);else if(cameraMode==='wide')desired.set(1050,480,1400);else{v.set(cameraMode==='side'?13:8,cameraMode==='side'?3:3.5,cameraMode==='side'?0:11).multiplyScalar(Math.max(1,1.05/camera.aspect));v.applyQuaternion(flight.quaternion);desired.copy(flight.position).add(v);}if(flight.mode==='flight')desired.y=Math.max(desired.y,obstacleCeiling(desired.x,desired.z)+10);camera.position.lerp(desired,1-Math.exp(-dt*4));if(flight.mode==='flight')camera.position.y=Math.max(camera.position.y,obstacleCeiling(camera.position.x,camera.position.z)+6);camera.lookAt(target);}else controls.update();
 sun.position.copy(flight.position).add(v.set(-35,65,25));sun.target.position.copy(flight.position);$('#state').textContent=labels[flight.state];$('#state-code').textContent=flight.state;$('#altitude').textContent=flight.position.y.toFixed(1);$('#lift-power').textContent=Math.round(flight.lift*100)+'%';$('#cruise-power').textContent=Math.round(flight.cruise*100)+'%';$<HTMLInputElement>('#timeline').value=String(flight.time);$('#time').textContent=flight.time.toFixed(1).padStart(4,'0')+' / '+flight.duration.toFixed(1)+' s';$('#play').textContent=flight.playing?'暂停':'播放';document.body.dataset.state=flight.state;
 aircraft.updateMatrixWorld();labelData.forEach((d,i)=>{const el=labelEls[i];el.hidden=!showLabels;v.copy(d.pos).applyMatrix4(aircraft.matrixWorld).project(camera);if(v.z>1||v.z<0)el.hidden=true;const x=Math.max(8,Math.min(canvas.clientWidth-165,(v.x*.5+.5)*canvas.clientWidth));el.style.transform=`translate(${x}px,${(-v.y*.5+.5)*canvas.clientHeight}px)`;});const mp=flight.routeProgress;missionMap.draw(mp,flight.position);mapWrap.querySelector('b')!.textContent=Math.round(mp*100)+'%';}renderer.render(scene,camera);document.body.dataset.geometries=String(renderer.info.memory.geometries);document.body.dataset.textures=String(renderer.info.memory.textures);document.body.dataset.drawCalls=String(renderer.info.render.calls);document.body.dataset.triangles=String(renderer.info.render.triangles);}
renderer.setAnimationLoop(animate);
Object.defineProperty(window,'ev50Diagnostics',{get:()=>({ready,time:flight?.time,duration:flight?.duration,route:flight?.route,state:flight?.state,mode:flight?.mode,playing:flight?.playing,loop:flight?.loop,rotors:rotors.length,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,position:aircraft.position.toArray(),camera:cameraMode,quality:$<HTMLSelectElement>('#quality').value})});
