"""依用户示意设置的低置概念驱动与单直件输出；不是原厂结构或制造尺寸。"""

DRIVE_AXIS_Z = .077
GUIDE_AXIS_Z = .065
CROSSBEAM_Z = .047
OUTPUT_SADDLE_Z = .055
OUTPUT_SADDLE_SIZE = (.026, .030, .014)
GUIDE_BRIDGE_Z = .0475
SUPPORT_FRAME_Z = .046
SCREW_PEDESTAL_TOP_Z = .061
GUIDE_PEDESTAL_TOP_Z = .054
SUPPORT_FOOT_TOP_Z = .051
MOTOR_MOUNT_Z = .030
MOTOR_SADDLE_Z = .047
MOTOR_FOOT_TOP_Z = .034
OUTPUT_CENTER_Y = -.009
OUTPUT_HALF_SPAN = .12
OUTPUT_LINK_RADIUS = .007
OUTPUT_STUD_DISTANCE = .030


def output_top_local(sign, slider_z):
    """横梁与每侧单直件共享端点；滑架纵向输入和两端球心不动。"""
    return (sign * OUTPUT_HALF_SPAN, OUTPUT_CENTER_Y, CROSSBEAM_Z - slider_z)
