/** Mandatory source + runtime full indexed strict self-contact gate. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {prepareMesh,scanMesh,assertCompleteModelReports,inheritFuselageContacts}from'./exact-self-geometry.mjs';
import {loadExactMeshes,sha256}from'./exact-self-load.mts';import{verifiedReference}from'../current/reference-records.mjs';
const root=process.env.QA_MODEL_ROOT??'.',out=process.env.QA_OUT??'qa/current/exact-self-contact-report.json',preflight=process.env.QA_PREFLIGHT==='1',nearDiagnostics=process.env.QA_EXACT_NEAR_DIAGNOSTICS!=='0',contract=JSON.parse(fs.readFileSync('qa/contracts/nacelle-wing-refinement.json','utf8'));
assert(preflight||contract.reviewed,'Reviewed contract required outside preflight');
if(!preflight){assert(process.env.QA_MODEL_ROOT===undefined,'QA_MODEL_ROOT is preflight-only; formal scan must use current frozen project');assert(process.env.QA_EXACT_NEAR_DIAGNOSTICS===undefined,'Formal proximity diagnostics may not be externally disabled');}
const domain={minimumAbsX:.2234,maximumAbsX:.6201,longitudinalY:[-2.0023,-.7299],verticalZ:[-.2700,.1322]};assert.deepEqual(Object.fromEntries(Object.keys(domain).map(k=>[k,contract.wingShape.centralAttachmentDomainBlender[k]])),domain,'Fixed reviewed deformation domain must not expand');
const previous=verifiedReference('nacelle-previous-reference.json'),ref=verifiedReference('exact-self-fuselage-reference.json');assert.equal(ref.data.referenceSha256,previous.sha256);assert.equal(previous.sha256,contract.previousAcceptedReferenceSha256);assert.equal(ref.data.formatVersion,1);assert.deepEqual(ref.data.models.map((m:any)=>m.encoding),['source','runtime']);const models:any[]=[];
for(const[encoding,file]of[['source','assets/blender/xp4-source.glb'],['runtime','public/models/xp4.glb']]){const a=await loadExactMeshes(path.join(root,file));if(!preflight)assert.equal(a.sha256,contract[encoding+'Sha256'],'Frozen reviewed candidate hash');const baseline=ref.data.models.find((m:any)=>m.encoding===encoding);assert.equal(baseline.modelSha256,previous.data.models.find((m:any)=>m.encoding===encoding).modelSha256);assert.equal(baseline.mesh.name,'Fuselage');const old=prepareMesh(baseline.mesh),oldReport=scanMesh(old),meshes=[];
 for(const mesh of a.meshes){const report=scanMesh(mesh,{nearDiagnostics});if(mesh.name==='Fuselage'){report.inheritance=inheritFuselageContacts(mesh,report,old,oldReport,domain);report.passed=report.inheritance.passed;}meshes.push(report);console.log(JSON.stringify({encoding,name:report.name,passed:report.passed,triangles:report.coverage.indexedTriangles,candidates:report.coverage.closedAABBCandidates,strictContacts:report.strictContactCount,classifications:report.classifications,degenerateTriangles:report.degenerateTriangles.length,inherited:report.inheritance?.inheritedCount,rejected:report.inheritance?.rejectedCount,milliseconds:report.milliseconds}));}
 assert.equal(sha256(fs.readFileSync(a.source)),a.sha256,'GLB changed during strict scan');models.push({encoding,source:a.source,sha256:a.sha256,meshes,baseline:{modelSha256:baseline.modelSha256,strictContactCount:oldReport.strictContactCount,coverage:oldReport.coverage,classifications:oldReport.classifications,degenerateTriangles:oldReport.degenerateTriangles}});
}
assertCompleteModelReports(models);const result={formatVersion:1,passed:models.every(m=>m.meshes.every((s:any)=>s.passed)),preflight,method:'All actual decoded indexed triangles, no relative degeneracy filtering; exact IEEE-754 dyadic integer/rational predicates; closed AABB BVH only as strict broad phase; shared simplex allowed only when it contains full exact intersection; no floating SAT candidate exclusion',coordinatePremise:'Each tested mesh is rigid/nonmorphed/noninstanced, with one verified invertible affine matrix. Exact self-intersection is invariant in mesh local coordinates; witnesses are integer homogeneous local coordinates times exactCoordinateScalePowerOfTwo. Decoded runtime is independently scanned.',domain,reference:{path:ref.path,sha256:ref.sha256},models,claim:'Discrete source/runtime mesh self-intersection only. No continuous motion, manufacturing, physical-clearance or browser pixel certification.'};fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,out}));if(!result.passed)process.exitCode=1;
