/** In-memory counterexample only. Never writes or changes a model or frozen QA input. */
import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const project=process.cwd();
const {verifyExactIndexedHostMaterial}=await import(project+'/qa/nacelle/host-indexed-exactness.mjs');
const {expectedHostDecorationSurface}=await import(project+'/qa/nacelle/host-decoration-preservation.mts');
const {subdivideOriginalSeam}=await import(project+'/qa/nacelle/host-decoration-subdivision.mts');
const {proveAccessoryTriangleBijection}=await import(project+'/qa/nacelle/accessory-preservation.mts');
const digest=(b:any)=>crypto.createHash('sha256').update(b).digest('hex');
const paths=['assets/blender/xp4-source.glb','qa/reference/nacelle-host-decoration-subdivision-reference.json','qa/reference/nacelle-previous-host-decorations.json','qa/reference/nacelle-previous-fuselage.json','qa/nacelle/host-decoration-preservation.mts','qa/nacelle/host-decoration-subdivision.mts','qa/nacelle/accessory-preservation.mts','qa/nacelle/host-indexed-exactness.mjs'];
const inputHashes=Object.fromEntries(paths.map(p=>[p,digest(fs.readFileSync(project+'/'+p))]));
assert.equal(inputHashes[paths[0]],'801b02ca6b12c326a04e0a1fe7741a99f168c629384ae836f490f7779428570e');assert.equal(inputHashes[paths[1]],'7c9b35fba54bf7abb80867e4f2955cb2959a6b12fc5e2c5e8fa03e24baa5a88d');assert.equal(inputHashes[paths[2]],'152134fbdd0b276b43cdaf6a38e5bce094e1e4dd09612a173712c23c4b7c6184');assert.equal(inputHashes[paths[3]],'85535d86587aed302ff6892175c4b430c2db55ee85a8023d2eb76fad2ba6ad48');
const native=JSON.parse(fs.readFileSync(project+'/'+paths[1],'utf8')),host=JSON.parse(fs.readFileSync(project+'/'+paths[3],'utf8')).models.find((m:any)=>m.encoding==='source'),rows=[];
for(const mesh of native.meshes){const original=mesh.surface,oldMap=expectedHostDecorationSurface(original,host),made=subdivideOriginalSeam(original,Array.from({length:16},(_,i)=>i)),expected=expectedHostDecorationSurface(made.surface,host).surface;
 const unusedOriginalIds=oldMap.mappings.map((m:any,i:number)=>m.delta===0?i:null).filter((i:any)=>i!==null),candidate={...expected,positions:expected.positions.map((p:number[])=>[p[0]+5e-7,p[1],p[2]])};candidate.positions.push(...unusedOriginalIds.map((i:number)=>[...original.positions[i]]));candidate.positionCount=candidate.positions.length;
 const geometry=proveAccessoryTriangleBijection(expected,candidate,1e-6),bufferKeys=new Set(candidate.positions.map((p:number[])=>p.join(','))),physicalKeys=new Set(candidate.indices.map((i:number)=>candidate.positions[i].join(',')));
 const lostExactOutside=unusedOriginalIds.filter((i:number)=>!bufferKeys.has(original.positions[i].join(','))),lostReferencedOutside=unusedOriginalIds.filter((i:number)=>!physicalKeys.has(original.positions[i].join(','))),used=new Set(candidate.indices),unusedBufferIds=Array.from({length:candidate.positionCount},(_,i)=>i).filter(i=>!used.has(i));
 assert.throws(()=>verifyExactIndexedHostMaterial({originalSurface:original,expectedSurface:expected,currentSurface:candidate,protectedOriginalFaces:Array.from({length:88},(_,i)=>i+16),unmovedExpectedVertexIds:oldMap.mappings.map((m:any,i:number)=>m.delta===0?i:null).filter((i:any)=>i!==null),correspondence:geometry.correspondence}));
 assert(geometry.passed);assert.equal(lostExactOutside.length,0);assert.equal(lostReferencedOutside.length,48);assert.equal(unusedBufferIds.length,48);
 rows.push({name:mesh.name,demonstrated:true,hardenedIndexedGateRejected:true,mutation:'Translate every indexed expected source point by +5e-7 GLTF X; append the 48 exact old zero-displacement points without indexing them. Keep all triangles, cyclic order, material and node metadata.',epsilon:1e-6,productionGeometryPassed:geometry.passed,maximumEndpointError:geometry.maximumEndpointError,productionLostExactOutsideCount:lostExactOutside.length,actuallyMissingOldOutsideMaterialPoints:lostReferencedOutside.length,expectedPositionCount:expected.positionCount,candidatePositionCount:candidate.positionCount,triangleCount:candidate.triangleCount,rawUnusedPositionIds:unusedBufferIds,lostReferencedOriginalVertexIds:lostReferencedOutside,correspondenceSha256:geometry.correspondenceSha256,completeTriangleAccounting:geometry.completeTriangleAccounting});}
for(const [p,h]of Object.entries(inputHashes))assert.equal(digest(fs.readFileSync(project+'/'+p)),h);
const result={passed:rows.every(r=>r.hardenedIndexedGateRejected),demonstrated:true,currentModelModified:false,sourceSha256:inputHashes[paths[0]],inputHashes,scriptSha256:digest(fs.readFileSync(fileURLToPath(import.meta.url))),createdAt:new Date().toISOString(),finding:'The archived original buffer-existence predicate accepts these in-memory counterexamples, but the hardened actual-indexed-material gate rejects both. No production asset was changed.',scope:'Reproduces the frozen verifier geometry + exactOutside acceptance predicates in memory; it does not claim the hypothetical modified GLB passes every other independent gate.',rows};
const out=process.env.QA_OUT??'qa/current/host-protection-supplement/unused-points-regression-report.json';fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({demonstrated:true,out,rows:rows.map(r=>({name:r.name,geometryPassed:r.productionGeometryPassed,lostExactOutside:r.productionLostExactOutsideCount,missingActualMaterial:r.actuallyMissingOldOutsideMaterialPoints,unused:r.rawUnusedPositionIds.length}))}));
