import fs from 'node:fs';import assert from 'node:assert/strict';import test from 'node:test';
import {verifiedReference}from'../current/reference-records.mjs';import{POWERTRAIN_IDS,powertrainInventory,referenceTransformGraph,verifyPoseTranslations}from'./powertrain-identity.mts';
import {reviewHingeDependencyMetadata} from './hinge-dependency-review.mjs';
import {runAccessoryPreservationRegressions} from './accessory-preservation.selftest.mts';
import {runHostDecorationRegressions} from './host-decoration-preservation.selftest.mts';
import {runHostIndexedExactnessRegressions} from './host-indexed-exactness.selftest.mjs';
const reference=verifiedReference('nacelle-previous-reference.json');assert.equal(reference.sha256,'417f7e24af6d8d523dafd90de5c824d5feaa9165b4506b111cc0d06419045d54');const nodes=reference.data.models.find(m=>m.encoding==='source').nodes,inventory=POWERTRAIN_IDS.map(id=>powertrainInventory(nodes,id));const deltas=Object.fromEntries(POWERTRAIN_IDS.map(id=>[id,[id.endsWith('Front')?(id[0]==='L'?.35:-.35):0,-.22,0]]));
function moved(filter:(name:string,item:any)=>boolean=(name,item)=>item.direct.includes(name),factor=(name:string,item:any)=>1){const out=structuredClone(nodes);for(const item of inventory)for(const n of out)if(filter(n.name,item))n.position=n.position.map((v,k)=>v+deltas[item.id][k]*factor(n.name,item));return out;}
const evaluate=(after:any[])=>verifyPoseTranslations(referenceTransformGraph(nodes),referenceTransformGraph(after),inventory,deltas,1e-6);
const hingeRaise=[0,.029,0];
function rebased(compensate=true){const out=moved();for(const n of out){if(/^WingPivot_[LR]$/.test(n.name))n.position=n.position.map((v,k)=>v+hingeRaise[k]);for(const item of inventory)if(compensate&&item.direct.includes(n.name))n.position=n.position.map((v,k)=>v-hingeRaise[k]);}return out;}
const rows=[];test('all four complete own-wing translations pass 123 distinct actual rig states',()=>{const report=evaluate(moved());assert(report.every(r=>r.passed));rows.push({name:'complete-translations',passed:true,rows:report.length,max:Math.max(...report.map(r=>r.maxPositionError))});});
test('moving only propellers rejects omitted nacelles and shaft hardware',()=>{assert.throws(()=>evaluate(moved((name,item)=>name==='Prop_'+item.id)),/桨毂中心偏离电机轴线/);rows.push({name:'propeller-only-negative',passed:true});});
test('moving descendant blades a second time rejects double displacement',()=>{assert(evaluate(moved((name,item)=>item.all.includes(name))).some(r=>!r.passed));rows.push({name:'descendant-double-move-negative',passed:true});});
test('world-space downward substitution rejects own-wing direction',()=>{const out=moved();for(const item of inventory)for(const n of out)if(item.direct.includes(n.name)){const old=nodes.find(o=>o.name===n.name);n.position=old.position.map((v,k)=>v+(k===2?-.22:0));}assert(evaluate(out).some(r=>!r.passed));rows.push({name:'wrong-down-axis-negative',passed:true});});
test('omitted axis marker and wrong-parent powertrain are rejected',()=>{assert.throws(()=>powertrainInventory(nodes.filter(n=>n.name!=='MotorAxisStart_L_Front'),'L_Front'));const out=structuredClone(nodes);out.find(n=>n.name==='Nacelle_L_Front').parent='WingPivot_R';assert.throws(()=>powertrainInventory(out,'L_Front'));rows.push({name:'missing-marker-wrong-parent-negative',passed:true});});
test('approved hinge raise and compensating own-wing rebase preserve complete 123-state relation',()=>{const report=verifyPoseTranslations(referenceTransformGraph(nodes),referenceTransformGraph(rebased()),inventory,deltas,1e-6,hingeRaise);assert(report.every(r=>r.passed));assert.equal(new Set(report.map(r=>r.wing)).size,41);rows.push({name:'hinge-rebase-complete-positive',passed:true,rows:report.length,max:Math.max(...report.map(r=>r.maxPositionError))});});
test('missing hinge rebase compensation cannot be passed as the same nacelle move',()=>{const report=verifyPoseTranslations(referenceTransformGraph(nodes),referenceTransformGraph(rebased(false)),inventory,deltas,1e-6,hingeRaise);assert(report.some(r=>!r.passed&&r.maxPositionError>.028));rows.push({name:'hinge-rebase-missing-compensation-negative',passed:true});});
test('ignoring the approved hinge raise rejects a physically compensated assembly',()=>{assert(evaluate(rebased()).some(r=>!r.passed&&r.maxPositionError>.028));rows.push({name:'hinge-rebase-old-world-law-negative',passed:true});});
const hingeDeclaration={deltaBlender:[0,0,.029],deltaGltf:hingeRaise,previousRightPivotBlender:[1.5,-1.47,-.22],rightPivotBlender:[1.5,-1.47,-.191]};
function dependencyFixture(){const out=structuredClone(reference.data.manifest),old=reference.data.manifest,minimum=1.0145352166,delta=minimum-old.mechanism.sliderTravel[0];out.mechanism.sliderTravel[0]=minimum;out.internalDrive.stroke[0]=minimum;for(const side of ['L','R'])out.mechanism.sides[side].wingAnchorLocal[1]-=.029;out.internalDrive.travelStopCentersBlenderY[0]+=delta;for(const row of out.internalDrive.fixedAttachmentInterfaces)if(/^Drive_FrontTravelStop_[LR]$/.test(row.pair[0]))for(const key of ['min','max'])row[key][2]-=delta;return out;}
test('explicit height dependency metadata permits only the approved rebase, stroke and front stop',()=>{const result=reviewHingeDependencyMetadata(reference.data.manifest,dependencyFixture(),hingeDeclaration);assert.equal(result.changes.length,9);assert(result.unchangedRodLength&&result.unchangedRearStop&&result.unchangedLowDriveFixedLayout);assert.equal(result.physicalAcceptanceEstablished,false);rows.push({name:'approved-metadata-dependencies-positive',passed:true});});
test('axis position, body anchor, rear stop, low drive, bore and unbound stroke changes reject',()=>{for(const mutate of [(x:any)=>x.internalDrive.travelStopCentersBlenderY[1]+=.001,(x:any)=>x.internalDrive.screwAxisHeightBlender+=.001,(x:any)=>x.mechanism.sides.L.bodyAnchorCruise[0]+=.001,(x:any)=>x.mechanism.sides.L.wingAnchorLocal[0]+=.001,(x:any)=>x.internalDrive.movingClearances.guideBoreRadius+=.001,(x:any)=>x.internalDrive.stroke[0]+=.001]){const next=dependencyFixture();mutate(next);assert.throws(()=>reviewHingeDependencyMetadata(reference.data.manifest,next,hingeDeclaration));}assert.throws(()=>reviewHingeDependencyMetadata(reference.data.manifest,dependencyFixture(),{...hingeDeclaration,rightPivotBlender:[1.51,-1.47,-.191]}));rows.push({name:'unapproved-metadata-dependencies-negative',passed:true});});
test('complete non-target accessory surface regressions retain every raw face and reject mutations',()=>{const report=runAccessoryPreservationRegressions();assert(report.passed);assert.equal(report.caseCount,31);assert(report.results.every(r=>r.passed));rows.push({name:'accessory-full-surface-positive-and-negative',passed:true,report});});
test('four host decoration exact mapping and unchanged thresholds reject missing or excessive repair',()=>{const report=runHostDecorationRegressions();assert(report.passed&&report.caseCount===19);rows.push({name:'fixed-host-decoration-mapping-positive-and-negative',passed:true,report});});
test('exact indexed host protection rejects orphan and wrong-face coordinate substitutions',()=>{const report=runHostIndexedExactnessRegressions();assert(report.passed&&report.caseCount===21&&report.results.every(r=>r.passed));rows.push({name:'host-indexed-source-exactness-positive-and-negative',passed:true,report});});
test.after(()=>{fs.writeFileSync(process.env.QA_OUT??'qa/current/powertrain-identity-selftest-report.json',JSON.stringify({passed:rows.length===13,referenceSha256:reference.sha256,checks:rows},null,2)+'\n');});
