/** Complete powertrains: explicit identities, own-wing affine motion, no shape/parent exemptions. */
import assert from 'node:assert/strict';import * as T from 'three';
import {createModelRig,applyModelPose,applyMotorPose}from'../../src/rig.ts';
import {MOTOR_IDS,newMotorStates}from'../../src/motors.ts';
export const POWERTRAIN_IDS=['L_Front','L_Rear','R_Front','R_Rear'] as const;
export const POWERTRAIN_PREFIXES=['Nacelle','Motor_cowl','Landing_wear_tip','Pod_U_access_panel','Cowl_boundary','Pod_wing_saddle','Pod_mount_seam','MotorAxisStart','MotorAxisEnd','Motor_spindle','Prop','MotorFrontBearing'];
export function directPowertrainName(name:string,id:string){return new RegExp('^(?:'+POWERTRAIN_PREFIXES.join('|')+')_'+id+'(?:001)?$').test(name);}
export function powertrainInventory(nodes:any[],id:string){const map=new Map(nodes.map(n=>[n.name,n]));const direct=nodes.filter(n=>directPowertrainName(n.name,id));assert.equal(direct.length,14,'Powertrain must have exactly fourteen direct wing attachments '+id);assert(direct.every(n=>n.parent==='WingPivot_'+id[0]),'Each powertrain root must remain attached to its own wing');const all=nodes.filter(n=>{for(let q=n;q;q=map.get(q.parent)){if(direct.some(p=>p.name===q.name))return true;}return false;});assert.equal(all.length,23,'Complete powertrain including nine rotor descendants '+id);assert.equal(all.filter(n=>n.isMesh).length,18);return {id,direct:direct.map(n=>n.name).sort(),all:all.map(n=>n.name).sort()};}
/** This is an exact frozen transform graph, explicitly not old mesh or old collision evidence. */
export function referenceTransformGraph(nodes:any[]){const map=new Map<string,T.Object3D>();for(const n of nodes){const o=new T.Object3D();o.name=n.name;o.position.fromArray(n.position);o.quaternion.fromArray(n.quaternion);o.scale.fromArray(n.scale);o.userData=JSON.parse(JSON.stringify(n.userData));map.set(n.name,o);}const roots=[];for(const n of nodes){const o=map.get(n.name)!;if(n.parent===null)roots.push(o);else{assert(map.has(n.parent),'Reference parent missing');map.get(n.parent)!.add(o);}}assert.equal(roots.length,1);return {scene:roots[0],nodes:map,rig:createModelRig(roots[0])};}
export function setPose(rig:any,wing:number,fold:number[],phases:number[]){applyModelPose(rig,wing);const motors=newMotorStates();for(const[i,id]of MOTOR_IDS.entries())motors[id]={rpm:fold[i]===0?900:0,phase:fold[i]===0?phases[i]:0,fold:fold[i],stage:fold[i]===0?'running':fold[i]===1?'folded':'folding',requested:fold[i]===0};applyMotorPose(rig,motors);rig.scene.updateMatrixWorld(true);}
export const PLACEMENT_POSES=Array.from({length:41},(_,i)=>i/40).flatMap(wing=>[
 {wing,fold:[1,1,1,1],phase:[0,0,0,0]},
 {wing,fold:[0,0,0,0],phase:[.17,1.1,2.3,4.9]},
 {wing,fold:[0,.25,.75,1],phase:[.73,0,0,0]},
]);
export function verifyPoseTranslations(before:any,after:any,inventories:any[],deltas:Record<string,number[]>,tolerance:number,hingeRebaseGltf:number[]=[0,0,0]){const rows=[];assert(hingeRebaseGltf.length===3&&hingeRebaseGltf.every(Number.isFinite));for(const pose of PLACEMENT_POSES){setPose(before.rig,pose.wing,pose.fold,pose.phase);setPose(after.rig,pose.wing,pose.fold,pose.phase);for(const item of inventories){const oldWing=before.scene.getObjectByName('WingPivot_'+item.id[0]),wing=after.scene.getObjectByName('WingPivot_'+item.id[0]);const delta=deltas[item.id].map((v,k)=>v-hingeRebaseGltf[k]);const worldMap=wing.matrixWorld.clone().multiply(new T.Matrix4().makeTranslation(delta[0],delta[1],delta[2])).multiply(oldWing.matrixWorld.clone().invert());let maxPositionError=0,maxLinearError=0;for(const name of item.all){const a=before.scene.getObjectByName(name),b=after.scene.getObjectByName(name);assert(a&&b,name);const expected=worldMap.clone().multiply(a.matrixWorld),p=new T.Vector3().setFromMatrixPosition(expected),q=new T.Vector3().setFromMatrixPosition(b.matrixWorld);maxPositionError=Math.max(maxPositionError,p.distanceTo(q));for(const index of [0,1,2,4,5,6,8,9,10])maxLinearError=Math.max(maxLinearError,Math.abs(expected.elements[index]-b.matrixWorld.elements[index]));}rows.push({id:item.id,...pose,nominalPowertrainDeltaWingLocal:deltas[item.id],hingeRebaseGltf,actualExpectedLocalDelta:delta,oldWingMatrix:oldWing.matrixWorld.toArray(),currentWingMatrix:wing.matrixWorld.toArray(),worldAffineMap:worldMap.toArray(),deltaWorld:new T.Vector3().setFromMatrixPosition(worldMap).toArray(),maxPositionError,maxLinearError,passed:maxPositionError<=tolerance&&maxLinearError<=tolerance});}}return rows;}
