/** Four complete assemblies, source and decoded runtime, bound to immutable pre-edit 55-stage evidence. */
import fs from 'node:fs';import assert from 'node:assert/strict';
import {verifiedReference}from'../current/reference-records.mjs';import {captureModelReference,compareModelReference,digest}from'../current/model-reference.mts';import {loadAudit}from'../current/audit-scene.mts';
import {POWERTRAIN_IDS,powertrainInventory,referenceTransformGraph,verifyPoseTranslations,PLACEMENT_POSES}from'./powertrain-identity.mts';
import {verifyAccessoryPreservation} from './accessory-preservation.mts';
import {verifyHostDecorationPreservation,HOST_DECORATION_RULE} from './host-decoration-preservation.mts';
const accessoryReference=verifiedReference('nacelle-previous-accessory-surfaces.json');
const reference=verifiedReference('nacelle-previous-reference.json'),summary=verifiedReference('nacelle-previous-summary.json');assert.equal(reference.sha256,'417f7e24af6d8d523dafd90de5c824d5feaa9165b4506b111cc0d06419045d54');assert.equal(summary.sha256,'475931954be31763db409dd96055d64a0d58edbb71f427e29fbfd07119d32fb4');assert.equal(reference.data.acceptedSummarySha256,summary.sha256);assert(summary.data.passed&&summary.data.stages.length===55&&summary.data.stages.every(s=>s.exitCode===0));
const c=JSON.parse(fs.readFileSync('qa/contracts/nacelle-wing-refinement.json','utf8'));assert(c.reviewed===true||process.env.QA_PREFLIGHT==='1');const manifest=JSON.parse(fs.readFileSync('public/models/manifest.json','utf8'));const hingeRebaseGltf=c.hingeRelocation?.deltaGltf??[0,0,0];assert(hingeRebaseGltf.length===3&&hingeRebaseGltf.every(Number.isFinite));const reports=[];
for(const[encoding,file]of [['source','assets/blender/xp4-source.glb'],['runtime','public/models/xp4.glb']]){const old=reference.data.models.find(m=>m.encoding===encoding),actual=await captureModelReference(file),audit=await loadAudit(file),previous=referenceTransformGraph(old.nodes),tol=encoding==='source'?1e-6:6e-5;assert.equal(audit.sha256,c[encoding+'Sha256']);const before=new Map(old.nodes.map(n=>[n.name,n])),after=new Map(actual.nodes.map(n=>[n.name,n])),failures=[],assemblies=[];const inventories=POWERTRAIN_IDS.map(id=>powertrainInventory(old.nodes,id));
 for(const item of inventories){const next=powertrainInventory(actual.nodes,item.id);assert.deepEqual(next,item,'Complete powertrain identity, parentage or node count changed');const declaration=c.assemblies.find(r=>r.id===item.id);assert(declaration);const delta=declaration.deltaGltfWingLocal;assert(delta.length===3&&delta.every(Number.isFinite));assert(delta[1]<0&&Math.abs(delta[2])<1e-12);assert(item.id.endsWith('Front')?delta[0]*(item.id[0]==='L'?-1:1)<0:delta[0]===0);const localRows=[];
 for(const name of item.all){const a:any=before.get(name),b:any=after.get(name),direct=item.direct.includes(name),expected=a.position.map((v,k)=>v+(direct?delta[k]-hingeRebaseGltf[k]:0)),positionError=Math.max(...b.position.map((v,k)=>Math.abs(v-expected[k]))),quaternionError=Math.max(...b.quaternion.map((v,k)=>Math.abs(v-a.quaternion[k]))),scaleError=Math.max(...b.scale.map((v,k)=>Math.abs(v-a.scale[k])));const positionGeometryEqual=!a.isMesh||['uniquePositionsSha256','orientedPositionTrianglesSha256','triangleCount'].every(k=>a.geometry[k]===b.geometry[k]);const row={name,direct,positionError,quaternionError,scaleError,positionGeometryEqual,parentEqual:a.parent===b.parent,metadataEqual:JSON.stringify(a.userData)===JSON.stringify(b.userData)};localRows.push(row);if(!row.parentEqual||!row.metadataEqual||positionError>tol||quaternionError>tol||scaleError>tol)failures.push({id:item.id,reason:'powertrain member does not share exact intended rigid transform/metadata',...row});if(encoding==='source'&&!positionGeometryEqual)failures.push({id:item.id,reason:'Powertrain source material shape changed; whole-assembly relocation is required',name});}
 assemblies.push({id:item.id,deltaGltfWingLocal:delta,directNodeCount:14,allNodeCount:23,meshCount:18,localRows});}
 const hostDecorationPreservation=await verifyHostDecorationPreservation(file,encoding as 'source'|'runtime');assert.deepEqual(c.hostDecorationRemap,HOST_DECORATION_RULE);assert.equal(hostDecorationPreservation.sha256,c[encoding+'Sha256']);if(!hostDecorationPreservation.passed)failures.push({reason:'fixed host decoration exceeded its explicitly reviewed host mapping',hostDecorationPreservation});
 const accessoryPreservation=await verifyAccessoryPreservation(file,encoding as 'source'|'runtime',accessoryReference);assert.equal(accessoryPreservation.sha256,c[encoding+'Sha256']);assert.equal(accessoryPreservation.referenceSha256,c.accessorySurfaceReferenceSha256);if(!accessoryPreservation.passed)failures.push({reason:'non-target wing accessory changed cruise material or structure',accessoryPreservation});
 const deltas=Object.fromEntries(c.assemblies.map(r=>[r.id,r.deltaGltfWingLocal])),motion=verifyPoseTranslations(previous,audit,inventories,deltas,tol,hingeRebaseGltf);for(const r of motion)if(!r.passed)failures.push({reason:'whole assembly is not a common own-wing translation at actual pose',...r});const change=compareModelReference(old,actual);if(c.previousChanges)assert.deepEqual(change,c.previousChanges[encoding]);reports.push({passed:!failures.length,encoding,source:file,sha256:audit.sha256,previousSha256:old.modelSha256,encodingTolerance:tol,assemblies,accessoryPreservation,hostDecorationPreservation,hingeRebaseGltf,motionStates:PLACEMENT_POSES.length,motionRows:motion,changes:change,failures});}
const report={passed:reports.every(r=>r.passed),referenceSha256:reference.sha256,reports,limits:['123 discrete wing/fold/phase states establish complete rigid placement under the explicitly reviewed hinge rebase and unchanged motor control graph, not continuous collision clearance','Full strict triangle/solid, support, motor-axis and swept rotor envelopes remain separate mandatory stages','Source raw position/oriented-triangle powertrain identity is mandatory; compressed-runtime geometry equivalence is independently established against current source']};fs.writeFileSync(process.env.QA_OUT??'qa/current/nacelle-placement-report.json',JSON.stringify(report,null,2)+'\n');console.log({passed:report.passed,failures:reports.flatMap(r=>r.failures),models:reports.map(r=>({encoding:r.encoding,assemblies:r.assemblies.length,motionStates:r.motionStates}))});if(!report.passed)process.exitCode=1;
