/** True material section comparison to the independently frozen immediate accepted aircraft. */
import fs from 'node:fs';import assert from 'node:assert/strict';import * as T from 'three';
import {loadAudit} from '../current/audit-scene.mts';
import {createWorldTriangles} from '../lib/triangle-contact.mjs';
import {verticalSectionLookup} from '../current/layered-sections.mts';
import {verifiedReference} from '../current/reference-records.mjs';
import {verifyFixedSurfaceTranslation,verifyCompleteSurfacePreservation} from './fixed-wing-surface-translation.mts';
import {verifyRepairSolidOrientation} from './repair-solid-orientation.mts';
import {createMicrofoldCorrectionContext} from './oriented-microfold-corrections.mts';
import {measureUndersideContinuity} from './underside-continuity.mts';
import {CENTRAL_LIFT,SHAFT_LIFT,MOVING_CONSTRUCTION_INSET,ENCODING_TOLERANCE,NATURAL_FIT_LIMIT,JOIN_LIMITS,verifyJoinContinuity,verifyAxisTranslation,verifyTranslatedMaterialSection,verifyNaturalBottom} from './wing-shape-logic.mts';
const manifest=JSON.parse(fs.readFileSync('public/models/manifest.json','utf8'));
const contract=JSON.parse(fs.readFileSync('qa/contracts/nacelle-wing-refinement.json','utf8')),design=JSON.parse(fs.readFileSync('qa/contracts/layered-wing-refinement.json','utf8')).design;
const preflight=process.env.QA_PREFLIGHT==='1';assert(preflight||contract.reviewed,'Formal shape QA requires reviewed contract');
assert.equal(contract.wingShape.centralLift,CENTRAL_LIFT);assert.equal(contract.wingShape.shaftLift,SHAFT_LIFT);assert.equal(contract.wingShape.movingSkinConstructionInset,MOVING_CONSTRUCTION_INSET);assert.deepEqual(contract.wingShape.encodingTolerance,ENCODING_TOLERANCE);assert.equal(contract.wingShape.maximumNaturalUndersideFitResidual,NATURAL_FIT_LIMIT);assert.deepEqual(contract.wingShape.interiorJoinContinuity,JOIN_LIMITS);
const reference=verifiedReference('nacelle-previous-reference.json');assert.equal(reference.sha256,contract.previousAcceptedReferenceSha256);
assert.deepEqual(design.curveKnotsBlender,reference.data.manifest.layeredWingJoint.design.curveKnotsBlender,'Natural-bottom main domain cannot shrink or move from the frozen accepted curve');
assert.deepEqual(design.panDomainBlender,{y:[-1.78,-1.05],innerAbsX:.653,outerInsetFromCurve:.015});
const curve=(y:number)=>{const knots=design.curveKnotsBlender,i=Math.max(0,Math.min(knots.length-2,knots.findIndex((p:any)=>p.y>=y)-1)),a=knots[i],b=knots[i+1],t=(y-a.y)/(b.y-a.y);return a.absX+t*(b.absX-a.absX);};
const fixedSurfaceReference=verifiedReference('nacelle-previous-fixed-wing.json');assert.equal(fixedSurfaceReference.data.referenceSha256,reference.sha256);
const movingRootReference=verifiedReference('nacelle-previous-moving-root.json');assert.equal(movingRootReference.data.referenceSha256,reference.sha256);
const repairReference=verifiedReference('nacelle-pre-repair-wing-reference.json');assert.equal(repairReference.sha256,contract.wingShape.repairSurfaceReferenceSha256);assert.equal(repairReference.data.sourceSha256,contract.wingShape.preRepairDesignSourceSha256);
assert.equal(repairReference.data.sourceSha256,'1b53025c0498d45ff505ea9e5990b836f14a714b56710609cd123dab14da860f','Self-intersection repair may not silently choose a different construction design reference');
assert.equal(repairReference.data.relativeDegenerateEpsilon,0);assert.deepEqual(repairReference.data.pose,{wing:1,fold:[1,1,1,1]});
const directionEvidence=verifiedReference('nacelle-oriented-repair-corrections-v2.json');assert.equal(directionEvidence.sha256,contract.wingShape.originalDirectionCorrections?.evidenceSha256);assert(preflight||contract.wingShape.originalDirectionCorrections.reviewed,'Formal original-direction corrections require separate explicit review');
const reports:any[]=[];
for(const [encoding,file]of [['source','assets/blender/xp4-source.glb'],['runtime','public/models/xp4.glb']] as const){
 const a=await loadAudit(file),old=reference.data.models.find((m:any)=>m.encoding===encoding),tolerance=ENCODING_TOLERANCE[encoding];assert(old);
 if(!preflight)assert.equal(a.sha256,contract[encoding+'Sha256']);a.pose({label:'independent natural underside / equal-thickness cruise sections',wing:1,fold:[1,1,1,1]});
 const rows:any[]=[],failures:any[]=[];
 for(const [side,sign]of [['L',-1],['R',1]]as const){
  const get=(s:string)=>{const o=a.scene.getObjectByName(s);assert(o);return o;},f=verticalSectionLookup(a.snap(get('Fixed_root_'+side))),m=verticalSectionLookup(a.snap(get('Composite_wing_'+side)));
  for(const name of ['Fixed_root_'+side,'Composite_wing_'+side]){const topology=a.topology.get(name);assert(topology.closed&&topology.componentCount===1,'Material sections require closed single-component skin '+name);}
  const start=get('RootAxisStart_'+side).getWorldPosition(new T.Vector3()).toArray(),end=get('RootAxisEnd_'+side).getWorldPosition(new T.Vector3()).toArray();
  const beforeStart=old.nodes.find((n:any)=>n.name==='RootAxisStart_'+side).position,beforeEnd=old.nodes.find((n:any)=>n.name==='RootAxisEnd_'+side).position;
  const shaftTranslation=verifyAxisTranslation(beforeStart,beforeEnd,start,end,tolerance);if(!shaftTranslation.passed)failures.push({side,kind:'shaft equal vertical translation',shaftTranslation});
  const previousSurface=fixedSurfaceReference.data.meshes.find((r:any)=>r.encoding===encoding&&r.name==='Fixed_root_'+side);assert(previousSurface&&previousSurface.modelSha256===old.modelSha256);
  const fixedMesh=get('Fixed_root_'+side) as T.Mesh,fullFixedSnapshot=createWorldTriangles(fixedMesh,{degenerateEpsilon:0}),fixedRawTriangleCount=(fixedMesh.geometry.index?.count??fixedMesh.geometry.attributes.position.count)/3;
  const fullFixedSurfaceTranslation=verifyFixedSurfaceTranslation(previousSurface,fullFixedSnapshot,fixedRawTriangleCount,createMicrofoldCorrectionContext(directionEvidence,contract.wingShape.originalDirectionCorrections,'Fixed_root_'+side,fixedSurfaceReference.sha256));if(!fullFixedSurfaceTranslation.passed)failures.push({side,kind:'full fixed-wing surface translation',fullFixedSurfaceTranslation});
  const repairSurfacePreservation=[];
  for(const meshName of ['Fixed_root_'+side,'Composite_wing_'+side]){
   const beforeRepair=repairReference.data.meshes.find((m:any)=>m.name===meshName);assert(beforeRepair,'Every actual wing requires its exact pre-repair design surface');
   const mesh=get(meshName) as T.Mesh,snapshot=meshName==='Fixed_root_'+side?fullFixedSnapshot:createWorldTriangles(mesh,{degenerateEpsilon:0}),rawTriangleCount=(mesh.geometry.index?.count??mesh.geometry.attributes.position.count)/3,result=verifyCompleteSurfacePreservation(beforeRepair,snapshot,rawTriangleCount,[0,0,0],createMicrofoldCorrectionContext(directionEvidence,contract.wingShape.originalDirectionCorrections,meshName,repairReference.sha256));
   const solidOrientation=verifyRepairSolidOrientation(snapshot);if(!solidOrientation.passed)failures.push({side,kind:'repair closed consistent positive solid orientation',mesh:meshName,solidOrientation});
   repairSurfacePreservation.push({mesh:meshName,solidOrientation,referenceRole:'Unaccepted construction design before local self-intersection repair; only a shape constraint, never inherited safety or acceptance',referenceSourceSha256:repairReference.data.sourceSha256,...result});if(!result.passed)failures.push({side,kind:'complete local-repair surface preservation',mesh:meshName,result});
  }
  const translated:any[]=[],natural:any[]=[],allFixedSections:any[]=[];
  for(const p of old.cruiseWingSections.filter((p:any)=>p.side===side)){
   const x=sign*p.x,z=-p.y,after=f(x,z),moving=m(x,z),result=verifyTranslatedMaterialSection(p.fixed,after,tolerance),fixedRow={x,y:p.y,before:p.fixed,after,...result};
   allFixedSections.push(fixedRow);if(!result.empty)translated.push(fixedRow);
   if(!result.passed)failures.push({side,kind:'complete fixed material/bore equal translation',...fixedRow});
   const inMain=p.y>=-1.78-1e-12&&p.y<=-1.05+1e-12&&p.x>=.653&&p.x<=curve(p.y)-.015;
   if(inMain){
    const naturalResult=verifyNaturalBottom(p.fixed,moving,MOVING_CONSTRUCTION_INSET,tolerance,NATURAL_FIT_LIMIT);natural.push({x,y:p.y,beforeFixed:p.fixed,moving,...naturalResult});if(!naturalResult.passed)failures.push({side,kind:'natural actual underside',x,y:p.y,beforeFixed:p.fixed,moving,...naturalResult});
   }
  }
  assert.equal(allFixedSections.length,old.cruiseWingSections.filter((p:any)=>p.side===side).length,'No original material or empty ray may be skipped');
  assert(translated.length>2000,'Central fixed-wing comparison must cover the full baseline area');assert(natural.length>1500,'Natural underside must cover the complete main overlap domain with no bore mask');
  const oldBottoms=natural.map(p=>p.beforeFixed.at(-1)).filter(Number.isFinite),newBottoms=natural.map(p=>p.moving.at(-1)).filter(Number.isFinite),naturalCurvatureHeightRange=Math.max(...oldBottoms)-Math.min(...oldBottoms),actualCurvatureHeightRange=Math.max(...newBottoms)-Math.min(...newBottoms);
  if(naturalCurvatureHeightRange<.015||actualCurvatureHeightRange<.015)failures.push({side,reason:'natural underside must retain a non-flat airfoil profile',naturalCurvatureHeightRange,actualCurvatureHeightRange});
  const stats=(r:any[],key:string)=>({minimum:Math.min(...r.map(x=>x[key])),maximum:Math.max(...r.map(x=>x[key])),maximumAbsolute:Math.max(...r.map(x=>Math.abs(x[key])))});
  const oldMovingRoot=movingRootReference.data.meshes.find((r:any)=>r.encoding===encoding&&r.name==='Composite_wing_'+side);assert(oldMovingRoot?.modelSha256===old.modelSha256);const rootGeometry=new T.BufferGeometry();rootGeometry.setAttribute('position',new T.BufferAttribute(new Float64Array(oldMovingRoot.positions.flat()),3));rootGeometry.setIndex(oldMovingRoot.indices.flat());const rootMesh=new T.Mesh(rootGeometry);rootMesh.updateMatrixWorld();const oldRootLookup=verticalSectionLookup(createWorldTriangles(rootMesh));
  const panMetadata=manifest.layeredWingJoint.lowerPans.find((p:any)=>p.side===side);assert(panMetadata?.outerJoinRowsBlender?.length>50,'Explicit join rows required for boundary classification');
  const undersideContinuity=measureUndersideContinuity(a.snap(get('Composite_wing_'+side)),start,end,tolerance,{outerJoinRowsBlender:panMetadata.outerJoinRowsBlender,sharedCruiseLoft:reference.data.manifest.surfaceRefinements.root.sharedCruiseLoft,rootYOffset:reference.data.manifest.layeredWingJoint.oldPivotBlender[1],rootZOffset:reference.data.manifest.layeredWingJoint.oldPivotBlender[2],previousMovingLookup:oldRootLookup});
  const interiorJoinZone=undersideContinuity.interiorActualJoinSummary,interiorJoinAcceptance=verifyJoinContinuity(interiorJoinZone,undersideContinuity.criticalEdgeProfiles.unresolved,JOIN_LIMITS,undersideContinuity.topologyFailures);if(!interiorJoinAcceptance.passed)failures.push({side,kind:'actual interior join continuity',interiorJoinAcceptance,interiorJoinZone});
  rows.push({side,shaftTranslation,fullFixedSurfaceTranslation,repairSurfacePreservation,undersideContinuity,interiorJoinAcceptance,fixedSectionCount:translated.length,fixedMaterialIntervalCount:translated.reduce((n,p)=>n+p.materialIntervalCount,0),allFixedRayCount:allFixedSections.length,emptyFixedRayCount:allFixedSections.filter(p=>p.empty).length,originalBoreInterruptedRayCount:translated.filter(p=>p.before.length>2).length,naturalBottomSectionCount:natural.length,boreExceptionCount:0,recoveredEmptyBoreRayCount:0,boreExceptions:[],boreFootprint:{method:'No fixed-wing surface, material interval, bore-wall interval or empty ray is excluded; original axis and complete fixed wing both translate vertically .029',axisStart:start,axisEnd:end,previousAxisStart:beforeStart,previousAxisEnd:beforeEnd,radius:.045,finiteCutterHalfLength:1.1,encodingMargin:tolerance,shaftLift:SHAFT_LIFT},centralLowerDelta:stats(translated,'lowerDelta'),centralUpperDelta:stats(translated,'upperDelta'),centralThicknessError:stats(translated,'thicknessError'),naturalBottomOffset:stats(natural,'bottomOffset'),naturalResidual:stats(natural,'residual'),naturalCurvatureHeightRange,actualCurvatureHeightRange,failedCentralSections:allFixedSections.filter(p=>!p.passed).length,failedCentralWitnesses:allFixedSections.filter(p=>!p.passed).slice(0,20),worstCentralSections:translated.slice().sort((a,b)=>Math.abs(b.thicknessError)-Math.abs(a.thicknessError)).slice(0,12),failedNaturalSections:natural.filter(p=>!p.passed).length,worstNaturalSections:natural.slice().sort((a,b)=>Math.abs(b.residual)-Math.abs(a.residual)).slice(0,12)});
 }
 reports.push({encoding,source:file,sha256:a.sha256,baselineModelSha256:old.modelSha256,encodingTolerance:tolerance,passed:!failures.length,rows,failureCount:failures.length,failures:failures.slice(0,40)});
}
const r={passed:reports.every(r=>r.passed),preflight,reference:{path:reference.path,sha256:reference.sha256},fixedSurfaceReference:{path:fixedSurfaceReference.path,sha256:fixedSurfaceReference.sha256},movingRootReference:{path:movingRootReference.path,sha256:movingRootReference.sha256},originalDirectionCorrections:{evidenceSha256:directionEvidence.sha256,reviewed:contract.wingShape.originalDirectionCorrections.reviewed,direction:'beforeToAfter',currentToOriginalAlwaysStrict:true},repairSurfaceReference:{path:repairReference.path,sha256:repairReference.sha256,sourceSha256:repairReference.data.sourceSha256,role:'Unaccepted pre-repair design, not a safety/acceptance baseline'},centralLift:CENTRAL_LIFT,shaftLift:SHAFT_LIFT,movingConstructionInset:MOVING_CONSTRUCTION_INSET,usesNormals:false,maximumNaturalUndersideFitResidual:NATURAL_FIT_LIMIT,interiorJoinLimits:JOIN_LIMITS,reports,scope:'All saved .01-grid actual triangle sections including every fixed bore interval and empty ray; complete fixed wing and unchanged-shape shaft both shift vertically .029; moving natural underside main domain has no bore mask',limitations:['No fixed-wing bore or empty ray is exempted. Bore solids, full-pan material, supports, real self-intersection and all-motion collision remain mandatory independent gates.','Actual finite triangle sections are numerical geometry evidence, not browser-pixel review or aerodynamic/manufacturing certification.']};
fs.writeFileSync(process.env.QA_OUT??'qa/current/wing-shape-report.json',JSON.stringify(r,null,2)+'\n');console.log({passed:r.passed,reports:reports.map(r=>({encoding:r.encoding,passed:r.passed,rows:r.rows.map(({boreExceptions,...x}:any)=>x),failureCount:r.failureCount,failures:r.failures.slice(0,5)}))});if(!r.passed)process.exitCode=1;
