/** 相邻装饰可保持原有开放端，但不可借贴合制造塌面、额外开口、非流形边或分离件。 */
export function decorationTopology(s:any){
 const ids=new Map<string,number>(),edges=new Map<string,{a:number,b:number,count:number,balance:number}>(),parents:number[]=[];let zeroArea=0,minimumArea=Infinity;
 const id=(p:number[])=>{if(!p.every(Number.isFinite))throw new Error('装饰顶点非有限');const k=p.map(x=>Math.round(x/1e-12)).join(',');if(!ids.has(k)){ids.set(k,ids.size);parents.push(parents.length);}return ids.get(k)!;};
 const root=(i:number):number=>parents[i]===i?i:(parents[i]=root(parents[i]));
 for(const t of s.triangles){const p=t.vertices,u=p[1].map((x,k)=>x-p[0][k]),v=p[2].map((x,k)=>x-p[0][k]),area=Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])/2;minimumArea=Math.min(minimumArea,area);if(area<=1e-18)zeroArea++;const vs=p.map(id);for(let k=0;k<3;k++){const a=vs[k],b=vs[(k+1)%3];parents[root(b)]=root(a);const key=a<b?`${a}/${b}`:`${b}/${a}`,e=edges.get(key)??{a:Math.min(a,b),b:Math.max(a,b),count:0,balance:0};e.count++;e.balance+=a<b?1:-1;edges.set(key,e);}}
 const boundary=[...edges.values()].filter(e=>e.count===1),adj=new Map<number,number[]>();for(const e of boundary)for(const[a,b]of[[e.a,e.b],[e.b,e.a]]){if(!adj.has(a))adj.set(a,[]);adj.get(a)!.push(b);}
 const seen=new Set<number>();let boundaryLoops=0;for(const a of adj.keys())if(!seen.has(a)){boundaryLoops++;const q=[a];while(q.length){const x=q.pop()!;if(seen.has(x))continue;seen.add(x);q.push(...adj.get(x)!);}}
 return {weldEpsilon:1e-12,closed:boundary.length===0,components:new Set([...ids.values()].map(root)).size,boundaryEdges:boundary.length,boundaryLoops,boundaryVerticesWithWrongDegree:[...adj].filter(([,ns])=>ns.length!==2).length,nonmanifoldEdges:[...edges.values()].filter(e=>e.count>2).length,inconsistentInteriorEdges:[...edges.values()].filter(e=>e.count===2&&e.balance!==0).length,zeroArea,minimumArea,skippedDegenerate:s.skippedDegenerate??0,triangles:s.triangles.length};
}
export function verifyDecorationTopologySummary(original:any,current:any){const passed=current.triangles>0&&current.closed===original.closed&&current.components===original.components&&current.boundaryLoops===original.boundaryLoops&&current.boundaryVerticesWithWrongDegree===0&&current.nonmanifoldEdges===0&&current.inconsistentInteriorEdges===0&&current.zeroArea===0&&current.skippedDegenerate===0;return {passed,original,current,meaning:'保留原开/闭合形式和边界环数，细分可增加边数；没有把开放装饰强制封成结构实体'};}
export function verifyDecorationTopology(before:any,after:any){return verifyDecorationTopologySummary(decorationTopology(before),decorationTopology(after));}
