/** Early candidate diagnostic only. Cannot substitute for the formal complete affected-scope audit. */
import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import * as T from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';import {MeshoptDecoder} from 'three/examples/jsm/libs/meshopt_decoder.module.js';import {createModelRig,applyModelPose} from '../../src/rig.ts';
import {loadAudit} from './audit-scene.mts';import {conservativeBoxesOverlap} from './broadphase.mts';import {exactPairCache} from './exact-pair-cache.mts';
import {intersectMeshTriangles,createWorldTriangles} from '../lib/triangle-contact.mjs';import {containedComponents,solidTopology} from '../lib/solid-contact.mjs';
const input=process.argv[2],out=process.argv[3];assert(input&&out);
const decorations=new Set(JSON.parse(fs.readFileSync('qa/contracts/supports.json','utf8')).decorations.map(d=>d.name));
const skinsOnly=process.argv.includes('--skins-only'),fullLinkage=process.argv.includes('--full-linkage'),linkageOnly=process.argv.includes('--linkage-only'),construction=skinsOnly||process.argv.includes('--construction');
const windowArg=process.argv.find(x=>x.startsWith('--window=')),range=windowArg?windowArg.slice(9).split(',').map(Number):[0,1,360];const[startU,endU,steps]=range;assert(range.length===3&&Number.isFinite(startU)&&Number.isFinite(endU)&&startU>=0&&endU<=1&&startU<endU&&Number.isInteger(steps)&&steps>=1);assert(!(skinsOnly&&fullLinkage));
const target=(name:string)=>linkageOnly?(/^(Fixed_root_|Composite_wing_|Wing_blue_leading_|Fuselage$|Brace)/.test(name)):fullLinkage&&name.startsWith('Brace')||(skinsOnly?/^(Fixed_root_[LR]$|Composite_wing_[LR]$|Fuselage$)/:/^(Fixed_root_|Composite_wing_|Root|BraceWingSeat_|BraceBallPin_.*_Wing|Fuselage$)/).test(name);
async function loadConstructionSkins(){
 const reference=skinsOnly?null:await loadAudit('assets/blender/xp4-source.glb');const groupReference=new Map(reference?.meshes.map(m=>[m.name,m])??[]);
 const b=fs.readFileSync(input),g=await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');const rig=createModelRig(g.scene),meshes:any[]=[],topology=new Map(),snapshots=new Map();
 g.scene.traverse((o:any)=>{if(o.isMesh&&target(o.name)){if(reference){const old=groupReference.get(o.name);assert(old,'Construction mesh missing from actual production motion-group reference '+o.name);assert.equal(o.parent?.name,old.parent?.name,'Construction diagnostic parent changed '+o.name);o.qaGroup=old.qaGroup;}else o.qaGroup=o.name.startsWith('Composite_wing_')?o.parent.name:'fixed';o.qaBox=new T.Box3();o.geometry.computeBoundingBox();meshes.push(o);}});if(skinsOnly)assert.equal(meshes.length,5);else assert(meshes.length>5);
 const pose=(p:any)=>{applyModelPose(rig,p.wing);g.scene.updateMatrixWorld(true);for(const m of meshes)m.qaBox.copy(m.geometry.boundingBox).applyMatrix4(m.matrixWorld);};
 const snap=(m:any)=>{const prior=snapshots.get(m);if(prior&&prior.matrixWorld.every((v:number,i:number)=>v===m.matrixWorld.elements[i]))return prior;const s=createWorldTriangles(m);snapshots.set(m,s);topology.set(m.name,solidTopology(s,1e-12));return s;};
 pose({wing:0});meshes.forEach(snap);for(const m of meshes){assert(topology.get(m.name).closed||decorations.has(m.name),"Construction structural material must be closed "+m.name);if(/^(Fuselage$|Fixed_root_[LR]$|Composite_wing_[LR]$)/.test(m.name))assert.equal(topology.get(m.name).componentCount,1,"Each actual main wing skin must be a single connected solid "+m.name);}const pairs=[];for(let i=0;i<meshes.length;i++)for(let j=i+1;j<meshes.length;j++){const a=meshes[i],b=meshes[j];if(a.qaGroup!==b.qaGroup)pairs.push({a,b,key:[a.name,b.name].sort().join(' / ')});}
 return {scene:g.scene,motionGroupReferenceSha256:reference?.sha256??null,sha256:crypto.createHash('sha256').update(b).digest('hex'),meshes,topology,pairs,pose,snap};
}
const a=await(construction?loadConstructionSkins():loadAudit(input)),cache=exactPairCache(),pairs=a.pairs.filter(p=>target(p.a.name)&&target(p.b.name));
const contacts=new Map<string,any>(),unknown=new Map<string,any>(),states=[];let tests=0,sat=0;
for(let i=0;i<=steps;i++){const u=startU+(endU-startU)*i/steps,state={wing:u,fold:[1,1,1,1],label:windowArg?'candidate explicit bounded root/linkage window':'candidate root/linkage full wing stroke'};states.push(state);a.pose(state);
 for(const p of pairs){if(!conservativeBoxesOverlap(p.a.qaBox,p.b.qaBox))continue;
  const {value:{r,c}}=cache.evaluate(p,()=>{const sa=a.snap(p.a),sb=a.snap(p.b),r=intersectMeshTriangles(sa,sb,{maxWitnesses:1,epsilon:1e-9});sat+=r.stats.triangleSATTests;tests++;return {r,c:r.intersects?[]:containedComponents(sa,sb,a.topology.get(p.a.name),a.topology.get(p.b.name))};});
  if(r.intersects||c.length){if(!contacts.has(p.key)){const v={pair:[p.a.name,p.b.name],firstState:state,witness:r.witnesses[0]??c[0],samples:0,contactWingStates:[]};contacts.set(p.key,v);console.log('FIRST_CONTACT',JSON.stringify(v));}contacts.get(p.key).samples++;contacts.get(p.key).lastState=state;contacts.get(p.key).contactWingStates.push(u);}
  for(const x of c.unresolved??[])unknown.set(p.key+'/'+x.container+'/'+x.reason,{pair:[p.a.name,p.b.name],state,...x,knownOpenDecoration:decorations.has(x.container)&&!a.topology.get(x.container).closed});
 }
 if(i%20===0)console.log(i,steps,'contacts',contacts.size,'SAT',sat);
}
const r={passed:contacts.size===0&&[...unknown.values()].every(x=>x.knownOpenDecoration&&x.reason==="开放或非流形容器"),diagnosticOnly:true,skinsOnly,construction,motionGroupReferenceSha256:a.motionGroupReferenceSha256??null,fullLinkage,linkageOnly,wingRange:[startU,endU],requestedSteps:steps,fullWingStroke:startU===0&&endU===1,selectedMeshes:a.meshes.filter(m=>target(m.name)).map(m=>m.name),source:input,sha256:a.sha256,topology:a.meshes.filter(m=>target(m.name)).map(m=>({name:m.name,closed:a.topology.get(m.name).closed,componentCount:a.topology.get(m.name).componentCount})),samples:states.length,states,relativePairs:pairs.length,triangleSATTests:sat,exactPairTests:tests,cache:cache.stats(),contacts:[...contacts.values()],unresolved:[...unknown.values()],limitations:['Root-selected early diagnostic only; rod/drive/rotor/control/body full affected-scope stages still required','Declared open decorative skins receive full surface SAT; unsupported solid-containment directions are explicitly reported, never claimed as resolved volume checks','Finite sampled poses are not a continuous sweep proof; no new contact exclusions or threshold relaxation','Skins-only mode is allowed only for a construction diagnostic with incomplete attachments; it can never enter formal acceptance']};fs.writeFileSync(out,JSON.stringify(r,null,2)+'\n');console.log({passed:r.passed,diagnosticOnly:true,contacts:r.contacts.length,out});if(!r.passed)process.exitCode=1;
