/** Pure actual-mesh counterexamples for the finite radial and complete-object clearance gate. */
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import * as T from 'three';
import {createWorldTriangles} from '../lib/triangle-contact.mjs';
import {measureFairingRadialWindow,verifyFairingClearancePair,projectedPolygonRadius,FAIRING_CLEARANCE_LIMITS} from './fairing-clearance.mts';
import {captureClearanceJson,assertClearanceJsonStable} from './fairing-clearance-evidence.mjs';
const axisStart=[0,-.155,0],axisEnd=[0,.155,0],checks:string[]=[];
const check=(name:string,fn:()=>void)=>{fn();checks.push(name);};
function snapshot(geometry:T.BufferGeometry,name:string,matrix?:T.Matrix4){const m=new T.Mesh(geometry);m.name=name;if(matrix)m.applyMatrix4(matrix);m.updateMatrixWorld(true);return createWorldTriangles(m);}
const cylinder=(radius=.044,height=.14)=>snapshot(new T.CylinderGeometry(radius,radius,height,72,1,false),'fairing');
function tube(inner=.045,outer=.075,height=.3){const vertices:number[]=[],indices:number[]=[],n=64;
 for(const y of [-height/2,height/2])for(const radius of [outer,inner])for(let i=0;i<n;i++){const angle=i*Math.PI*2/n;vertices.push(radius*Math.cos(angle),y,radius*Math.sin(angle));}
 const quad=(a:number,b:number,c:number,d:number)=>indices.push(a,b,c,a,c,d);
 for(let i=0;i<n;i++){const j=(i+1)%n;quad(i,2*n+i,2*n+j,j);quad(n+i,n+j,3*n+j,3*n+i);quad(i,j,n+j,n+i);quad(2*n+i,3*n+i,3*n+j,2*n+j);}
 const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setIndex(indices);return snapshot(g,'wing-host');
}
const vertices=(s:any)=>s.triangles.flatMap((t:any)=>t.vertices),fairing=cylinder(),host=tube();
const core=(a=fairing,b=host)=>verifyFairingClearancePair(a,b,axisStart,axisEnd,'source',vertices(a));
check('closed concentric actual solids retain a positive polygon-aware radial bound and no intersection/containment',()=>{const r=core();assert(r.passed);assert(r.radial.actualRadialGap!>.0009);assert(r.radial.finiteHostFaceCount>0);assert(!r.supporting&&!r.addsSupportGraphEdge&&!r.collisionExemption);assert(r.fullObjectCollisionEstablished&&r.shellMeridianProofRequiredSeparately);});
check('all host triangle interiors are considered, not just distant triangle vertices',()=>{const polygon=[new T.Vector3(.1,0,0),new T.Vector3(-.05,0,.09),new T.Vector3(-.05,0,-.09)];const r=projectedPolygonRadius(polygon,new T.Vector3(),new T.Vector3(0,1,0));assert(r.minimum<1e-12);const h={sourceTriangleCount:1,skippedDegenerate:0,triangles:[{triangleIndex:0,vertices:polygon.map(p=>p.toArray())}]};assert(!measureFairingRadialWindow(vertices(fairing),h,axisStart,axisEnd,'source').passed);});
check('projected polygon edge minima are included even when all vertices exceed the bore radius',()=>{const p=[new T.Vector3(-.1,0,.02),new T.Vector3(.1,0,.02)];assert(Math.abs(projectedPolygonRadius(p,new T.Vector3(),new T.Vector3(0,1,0)).minimum-.02)<1e-12);});
check('coincident vertices at axial tangency remain finite evidence and cannot create a NaN pass or crash',()=>{const p=new T.Vector3(.045,0,0),r=projectedPolygonRadius([p,p.clone()],new T.Vector3(),new T.Vector3(0,1,0));assert.equal(r.minimum,.045);const h={sourceTriangleCount:1,skippedDegenerate:0,triangles:[{triangleIndex:0,vertices:[[.045,.07,0],[.1,.2,0],[.045,.2,.1]]}]};const measured=measureFairingRadialWindow(vertices(fairing),h,axisStart,axisEnd,'source');assert(!measured.passed&&measured.finiteHostFaceCount===0);});
check('axial clipping uses the whole finite triangle portion rather than a global vertex minimum',()=>{const h={sourceTriangleCount:1,skippedDegenerate:0,triangles:[{triangleIndex:0,vertices:[[.2,-.2,-.1],[.2,-.2,.1],[0,1,0]]}]};const r=measureFairingRadialWindow(vertices(fairing),h,axisStart,axisEnd,'source');assert(r.passed&&r.minimumHostRadius!>.1&&r.clippedPolygonCount===1);});
check('absence of a finite actual host face in the axial window is not clearance proof',()=>{const h={sourceTriangleCount:1,skippedDegenerate:0,triangles:[{triangleIndex:0,vertices:[[.1,1,0],[.2,1,.1],[.2,1,-.1]]}]};const r=measureFairingRadialWindow(vertices(fairing),h,axisStart,axisEnd,'source');assert(!r.passed&&r.finiteHostFaceCount===0&&r.actualRadialGap===null);});
check('the old oversize fairing fails the unchanged actual maximum-radius bound',()=>{assert(!core(cylinder(.054),host).passed);});
check('positive separation alone cannot bypass the reviewed wing-bore radius',()=>{const r=core(fairing,tube(.0446));assert(!r.passed&&r.radial.actualRadialGap!>0&&r.radial.minimumHostRadius!<r.radial.minimumRequiredHostRadius);});
check('actual fairing/host intersection remains failure',()=>{const shifted=snapshot(new T.CylinderGeometry(.044,.044,.14,72,1,false),'offset-fairing',new T.Matrix4().makeTranslation(.003,0,0)),r=core(shifted,host);assert(!r.passed&&r.surface.intersects);});
check('closed solid host containment defeats a seemingly clear finite radial surface window',()=>{const solidHost=snapshot(new T.CylinderGeometry(.075,.075,.3,64,1,false),'solid-host'),r=core(fairing,solidHost);assert(r.radial.passed&&!r.surface.intersects&&!r.passed&&r.containedComponents.some(x=>x.contained==='fairing'));});
check('a contained component representative in the original 1e-8 boundary band stays unresolved despite clear 1e-9 SAT',()=>{const solidHost=snapshot(new T.CylinderGeometry(.075,.075,.14000001,64,1,false),'boundary-band-host'),r=core(fairing,solidHost);assert(r.radial.passed&&!r.surface.intersects&&!r.passed&&!r.fullObjectCollisionEstablished);assert(r.containmentUnresolved.some(x=>x.reason==='boundary-representative-at-original-solid-epsilon'));});
check('reverse containment is also checked using actual complete objects',()=>{const smallHost=snapshot(new T.CylinderGeometry(.01,.01,.04,32,1,false),'inside-fairing-host'),r=core(fairing,smallHost);assert(!r.passed&&r.containedComponents.some(x=>x.contained==='inside-fairing-host'));});
check('open fairing triangles never establish solid clearance',()=>{const g=new T.CylinderGeometry(.044,.044,.14,72,1,false),index=Array.from(g.index!.array);index.splice(0,3);g.setIndex(index);const r=core(snapshot(g,'open-fairing'),host);assert(!r.passed&&!r.fairingTopology.closed);});
check('a disconnected extra fairing component cannot pass a radial-only argument',()=>{const a=cylinder(.02,.02),g=new T.BufferGeometry(),points:number[]=[];for(const shift of [-.04,.04])for(const t of a.triangles)for(const p of t.vertices)points.push(p[0],p[1]+shift,p[2]);g.setAttribute('position',new T.Float32BufferAttribute(points,3));const r=core(snapshot(g,'split-fairing'),host);assert(!r.passed&&r.fairingTopology.componentCount===2);});
check('arbitrary translated and rotated real axis markers preserve the measurement',()=>{const matrix=new T.Matrix4().makeRotationZ(.713);matrix.setPosition(1.5,-.22,1.47);const transform=(s:any,name:string)=>{const g=new T.BufferGeometry(),points=s.triangles.flatMap((t:any)=>t.vertices.flatMap((p:number[])=>new T.Vector3(...p).applyMatrix4(matrix).toArray()));g.setAttribute('position',new T.BufferAttribute(new Float64Array(points),3));return snapshot(g,name);};const a=transform(fairing,'posed-fairing'),b=transform(host,'posed-host'),start=new T.Vector3(...axisStart).applyMatrix4(matrix).toArray(),end=new T.Vector3(...axisEnd).applyMatrix4(matrix).toArray(),r=verifyFairingClearancePair(a,b,start,end,'source',vertices(a));assert(r.passed);assert(Math.abs(r.radial.actualRadialGap!-core().radial.actualRadialGap!)<1e-12);});
check('all decoded fairing vertices participate in the radial maximum',()=>{const r=verifyFairingClearancePair(fairing,host,axisStart,axisEnd,'source',[...vertices(fairing),[.06,0,0]]);assert(!r.passed&&r.radial.maximumFairingRadius===.06);});
const withOmittedTriangle=(s:any,name:string)=>{const points=[...vertices(s).flat(),0,-.05,0,0,.05,0,1e-16,0,0],g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(new Float64Array(points),3));return snapshot(g,name);};
check('a nonzero-area bore-intruding host face omitted by the legacy snapshot filter cannot pass',()=>{const omitted=withOmittedTriangle(host,'omitted-host');assert.equal(omitted.skippedDegenerate,1);assert.equal(omitted.sourceTriangleCount,omitted.triangles.length+1);const r=core(fairing,omitted);assert(!r.passed&&!r.radial.passed&&!r.allObjectFacesChecked&&!r.fullObjectCollisionEstablished);});
check('omitted fairing triangles also prevent the all-face and complete-object claims',()=>{const omitted=withOmittedTriangle(fairing,'omitted-fairing'),r=core(omitted,host);assert.equal(omitted.skippedDegenerate,1);assert(!r.passed&&!r.allObjectFacesChecked&&!r.fairingTriangleCoverage.passed);});
check('source triangle count and source index coverage are independently required',()=>{const countMismatch={...host,sourceTriangleCount:host.sourceTriangleCount+1,skippedDegenerate:0};assert(!core(fairing,countMismatch).passed);const duplicate={...host,triangles:host.triangles.map((t:any,i:number)=>i===1?{...t,triangleIndex:0}:t)};assert(!core(fairing,duplicate).passed);});
check('contract evidence hashes describe initially parsed bytes and reject any mid-run replacement',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'fairing-contract-test-')),file=path.join(dir,'input.json');try{const original='{"limit":1}\n';fs.writeFileSync(file,original);const evidence=captureClearanceJson(file);assert.equal(evidence.data.limit,1);assertClearanceJsonStable(evidence);fs.writeFileSync(file,'{"limit":2}\n');assert.notEqual(captureClearanceJson(file).sha256,evidence.sha256);assert.throws(()=>assertClearanceJsonStable(evidence),/changed during verification/);assert.equal(evidence.data.limit,1);fs.writeFileSync(file,original);assertClearanceJsonStable(evidence);}finally{fs.rmSync(dir,{recursive:true});}});
check('unknown encodings, degenerate axes and nonfinite actual coordinates fail closed',()=>{assert.throws(()=>measureFairingRadialWindow(vertices(fairing),host,axisStart,axisEnd,'relaxed' as any));assert.throws(()=>measureFairingRadialWindow(vertices(fairing),host,axisStart,axisStart,'source'));assert.throws(()=>measureFairingRadialWindow([[NaN,0,0]],host,axisStart,axisEnd,'source'));});
check('original source/runtime encoding and SAT/solid/weld thresholds remain exact',()=>{assert.deepEqual(FAIRING_CLEARANCE_LIMITS.encodingTolerance,{source:1e-6,runtime:6e-5});assert.equal(FAIRING_CLEARANCE_LIMITS.sat,1e-9);assert.equal(FAIRING_CLEARANCE_LIMITS.solid,1e-8);assert.equal(FAIRING_CLEARANCE_LIMITS.weld,1e-12);const r=measureFairingRadialWindow(vertices(fairing),host,axisStart,axisEnd,'runtime');assert(r.passed&&r.guaranteedDesignRadialLowerBound>.0008);});
const report={passed:true,checks:checks.length,cases:checks,noProductionModelsLoaded:true};if(process.env.QA_OUT)fs.writeFileSync(process.env.QA_OUT,JSON.stringify(report,null,2)+'\n');console.log(report);
