/** 当前工程只对比实际源/解码运行模型；旧完整模型留在原开发归档，不充作本轮重跑。 */
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import{verifyMotionReferenceInputs}from'./motion-reference-adapter.mjs';
import{validateMotionReference,captureAuditMotion,compareMotionCapture,fileSha256,sha256,assertSamePoseGrid}from'./motion-reference.mts';
import{affectedScope,assertMotionImpactCovered}from'./affected-scope.mts';import{loadAudit}from'./audit-scene.mts';
const args=process.argv.slice(2),command=args.shift();assert.equal(command,'compare','当前工程入口为compare，历史参照生成必须使用原开发归档');
const value=(flag:string,fallback?:string)=>{const i=args.indexOf(flag);if(i<0)return fallback;assert(args[i+1]&&!args[i+1].startsWith('--'));return args[i+1];};
const referenceRecord=verifyMotionReferenceInputs(),reference=validateMotionReference(referenceRecord.data);assertSamePoseGrid(reference.grid);
const scopeFile=value('--scope','qa/contracts/fuselage-slot-refinement.json')!,scope=JSON.parse(fs.readFileSync(scopeFile,'utf8')),requested=value('--encoding','both');assert(['both','source','runtime'].includes(requested!));
const specifications=[{encoding:'source',file:value('--source','assets/blender/xp4-source.glb')!},{encoding:'runtime',file:value('--runtime','public/models/xp4.glb')!}].filter(s=>requested==='both'||s.encoding===requested),reports:any[]=[];
for(const spec of specifications){const audit=await loadAudit(spec.file),current=captureAuditMotion(audit,reference.grid,(group,count)=>console.error(`逐态恒等 ${spec.encoding} ${group} ${count}`)),baseline=reference.models.find(m=>m.encoding===spec.encoding)!,comparison=compareMotionCapture(baseline,current,reference.grid,{allowedAddedMeshes:scope.addedNodes??[]}),impact=affectedScope(audit.scene,scope);assertMotionImpactCovered(impact,comparison);assert.equal(fileSha256(spec.file),audit.sha256);reports.push({...comparison,encoding:spec.encoding,source:spec.file,currentCapture:current,affectedScope:impact});}
assert.equal(verifyMotionReferenceInputs().sha256,referenceRecord.sha256);if(reports.length===2)assert.deepEqual(reports[0].currentCapture.meshes.map(m=>m.name),reports[1].currentCapture.meshes.map(m=>m.name));
const names=reports[0].currentCapture.meshes.map(m=>m.name),changedMotionMeshes=names.filter(n=>reports.some(r=>r.changedMotionMeshes.includes(n))),declaredRerunMeshes=[...new Set<string>(reports.flatMap(r=>r.affectedScope.rerunMeshes))].sort();
const report={passed:true,referenceSha256:referenceRecord.sha256,sourceAndDecodedRuntimeCompared:reports.length===2,stateCount:reference.grid.stateCount,stateParametersSha256:reference.grid.stateParametersSha256,declaredRerunMeshes,changedMotionMeshes,exactMotionMeshes:names.filter(n=>!changedMotionMeshes.includes(n)),inheritanceEligibleMeshes:names.filter(n=>reports.every(r=>r.inheritanceEligibleMeshes.includes(n))),rerunMeshes:names.filter(n=>reports.some(r=>r.rerunMeshes.includes(n))),dependencyProofs:referenceRecord.dependencyProofs,gridOrigin:referenceRecord.gridOrigin,methodOrigin:referenceRecord.methodOrigin,reports,claim:'通过仅表示参照/姿态/执行完整且所有差异都在重跑范围，不能视为碰撞验收通过。'};
const out=value('--out');assert(out,'必须给出独立报告路径');fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log({passed:true,out,declaredRerunMeshes:declaredRerunMeshes.length,exactMotionMeshes:report.exactMotionMeshes.length});
