/** 单工程验收的紧凑数学参照：严格指纹与必要旧材料面，不加载旧整机。 */
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import * as T from 'three';
import {createWorldTriangles} from '../lib/triangle-contact.mjs';import {solidTopology} from '../lib/solid-contact.mjs';
export const REFERENCE_DIR='qa/reference';
export const sha256=(bytes:any)=>crypto.createHash('sha256').update(bytes).digest('hex');
function verified(name:string){const p=path.join(REFERENCE_DIR,name),manifest=JSON.parse(fs.readFileSync(path.join(REFERENCE_DIR,'reference-manifest.json'),'utf8')),record=manifest.artifacts.find((r:any)=>path.basename(r.path)===name);assert(record,'参照清单缺少 '+name);const bytes=fs.readFileSync(p);assert.equal(sha256(bytes),record.sha256,'参照字节漂移 '+name);return {path:p,sha256:record.sha256,data:JSON.parse(bytes.toString())};}
export function loadAcceptedReference(){const r=verified('accepted-reference.json');assert.equal(r.data.formatVersion,1);assert.deepEqual(r.data.models.map((m:any)=>m.encoding),['source','runtime']);for(const m of r.data.models){assert.equal(m.nodes.filter((n:any)=>n.isMesh).length,283);assert.equal(new Set(m.nodes.map((n:any)=>n.name)).size,m.nodes.length);}return r;}
export function loadReferenceAudit(){const r=verified('source-protected-surfaces.json'),accepted=loadAcceptedReference(),expected=accepted.data.models.find((m:any)=>m.encoding==='source').acceptedModelSha256;assert.equal(r.data.acceptedModelSha256,expected);const scene=new T.Group(),snapshots=new Map<string,any>(),topology=new Map<string,any>();
 for(const item of r.data.meshes){assert.equal(item.triangles.length,item.sourceTriangleIndices.length);const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(new Float64Array(item.worldPositions.flat()),3));geometry.setIndex(item.triangles.flat());const mesh=new T.Mesh(geometry);mesh.name=item.name;scene.add(mesh);scene.updateMatrixWorld(true);const snap=createWorldTriangles(mesh);assert.equal(snap.triangles.length,item.triangles.length,'参照重建丢失真实面');for(const t of snap.triangles)t.triangleIndex=item.sourceTriangleIndices[t.triangleIndex];snap.sourceTriangleCount=item.sourceTriangleCount;snap.skippedDegenerate=item.skippedDegenerate;snapshots.set(item.name,snap);topology.set(item.name,solidTopology(snap,1e-12));}
 assert.equal(snapshots.size,8);return {referenceOnly:true,source:r.path,sha256:r.sha256,acceptedModelSha256:expected,scene,topology,snap:(mesh:any)=>{assert(snapshots.has(mesh.name),'参照仅保留必要改动件材料面 '+mesh.name);return snapshots.get(mesh.name);},pose:()=>{throw new Error('精简参照不是旧整机；不得假装重跑旧机构运动');}};
}
/** 节点代理只提供已记录的严格预期值；不会伪造缺失顶点或旧动画样本。 */
export function referenceNodeMap(model:any){return new Map<string,any>(model.nodes.map((n:any)=>[n.name,{name:n.name,parent:n.parent===null?null:{name:n.parent},isMesh:n.isMesh?true:undefined,visible:n.visible,userData:n.userData,_reference:n,matrix:{elements:n.localMatrix},position:{toArray:()=>n.position},quaternion:{toArray:()=>n.quaternion},scale:{toArray:()=>n.scale},updateMatrix:()=>{},material:n.material?{...n.material,color:{toArray:()=>n.material.color}}:undefined}]));}
