/** Immediate-edit impact is distinct from the older collision-inheritance checkpoint. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {verifiedReference} from './reference-records.mjs';import {compareMotionCapture} from './motion-reference.mts';
const prior=verifiedReference('previous-accepted-motion.json'),summary=verifiedReference('previous-accepted-summary.json'),model=verifiedReference('previous-accepted-reference.json'),grid=verifiedReference('accepted-motion-reference.json').data.grid;
assert.equal(prior.sha256,'3f21f5935f36ffaf0e10882c213bdc5ed90a56596d67845d51f0247db8d64786');assert.equal(summary.sha256,model.data.acceptedSummarySha256);assert.equal(prior.data.acceptedSummarySha256,summary.sha256);assert(summary.data.passed&&summary.data.stages.length===44&&summary.data.stages.every(s=>s.exitCode===0));
assert.equal(prior.data.stateCount,grid.stateCount);assert.equal(prior.data.stateParametersSha256,grid.stateParametersSha256);
const dir=process.env.QA_DIR??'qa/current/results',current=JSON.parse(fs.readFileSync(path.join(dir,'motion-identity-report.json'),'utf8'));assert(current.passed&&current.sourceAndDecodedRuntimeCompared);assert.equal(current.stateParametersSha256,grid.stateParametersSha256);
const reports=prior.data.models.map(previous=>{assert.equal(previous.modelSha256,summary.data[previous.encoding+'Sha256']);const actual=current.reports.find(r=>r.encoding===previous.encoding);assert(actual);const comparison=compareMotionCapture(previous,actual.currentCapture,grid,{allowedAddedMeshes:[]});
 for(const name of comparison.rerunMeshes)assert(actual.affectedScope.rerunMeshes.includes(name),'Immediate current-edit dependency was omitted from full physical rerun '+name);
 return {encoding:previous.encoding,source:actual.source,sha256:actual.currentModelSha256,previousModelSha256:previous.modelSha256,...comparison};});
const names=current.reports[0].currentCapture.meshes.map(m=>m.name),r={passed:true,previousReference:{path:prior.path,sha256:prior.sha256},stateCount:grid.stateCount,stateParametersSha256:grid.stateParametersSha256,reports,immediateGeometryOrMotionChangedMeshes:names.filter(n=>reports.some(r=>r.rerunMeshes.includes(n))),immediateMotionChangedMeshes:names.filter(n=>reports.some(r=>r.changedMotionMeshes.includes(n))),cumulativeHistoricalRerunMeshes:current.declaredRerunMeshes,claim:'Immediate previous current mesh/matrix/ancestry changes are all covered by the formal conservative rerun scope; older historical identity remains separately verified before any pair inheritance'};
fs.writeFileSync(process.env.QA_OUT??path.join(dir,'layered-motion-impact-report.json'),JSON.stringify(r,null,2)+'\n');console.log({passed:true,immediateAffected:r.immediateGeometryOrMotionChangedMeshes.length,cumulativeRerun:r.cumulativeHistoricalRerunMeshes.length});
