"""V25当前清单；旧证据保留在冻结基线，不冒用为新几何验收。"""
from pathlib import Path
import os,json,hashlib,struct,copy,math
ROOT=Path(__file__).resolve().parents[2];QA=ROOT/'qa/revision-20261007';STAGE=QA/'baked-candidate'
base_path=ROOT/'assets/baseline-20261007/manifest.json';base=json.loads(base_path.read_text());doc_bytes=(STAGE/'xp4-source.glb').read_bytes();doc=json.loads(doc_bytes[20:20+struct.unpack_from('<I',doc_bytes,12)[0]]);contract=doc['extras']['annotatedMechanism'];validation=json.loads((STAGE/'model-validation.json').read_text());encoding=json.loads((STAGE/'model-manifest.json').read_text())['assetEncoding']
keep=['referenceBaseline','coordinateSystem','authoredPose','transition','propellerSpinLocalAxis','motorAxisMarkers','propellerPlane','outerBladeFoldLocalAxis','outerBladeFoldAngles','pivotAngleMeaning','rotorHandedness','spinnerAxleClearance','rodEndSeat','foldingHinge','unitBoundary','straightFuselageSlot','nativeDriveConstraintV22']
manifest={k:copy.deepcopy(base[k])for k in keep};manifest['version']=25
manifest['annotationRevision']={'id':'2026-10-07-v25','baselineCommit':'7dcd5cde3a650c48a164c72bd9473671ec74b641','baselineManifest':'assets/baseline-20261007/manifest.json','baselineManifestSha256':hashlib.sha256(base_path.read_bytes()).hexdigest(),'supersedesBaselineGeometryEvidence':True,'old82ConstructionInputsUnchanged':True,'units':'原创概念模型单位u，非实机测绘尺寸','jointRightCruiseBlender':contract['actualRightPivot'],'hingeLinearScale':2,'shaftMaximumDiameter':.056,'shaftLength':.108,'frontNacelleAdditionalHoverWorldDeltaBlender':[0,-.16,0],'rearNacelles':{'additionalLayoutDelta':[0,0,0],'cruiseWorldPosePreserved':True,'pivotLocalRebaseApplied':True,'hoverAndTransitionTrajectoriesRecomputed':True},'lowerSkin':{'nodes':['WingLowerClosure_L','WingLowerClosure_R'],'nominalVerticalThickness':.012,'closedConnectedComponentsPerSide':1,'designedAxisBoreRetained':True},'claimBoundary':'本轮受影响域及明确有限姿态检查；不继承旧材料/运动证书，不代表连续全部状态、制造或适航安全认证','reviewStatus':'本地验证进行中，未远端发布','currentEvidenceRoot':'qa/revision-20261007','sourceCandidateSha256':hashlib.sha256((QA/(os.environ.get('TRANSWING_REVISION_LABEL','candidate-final')+'.blend')).read_bytes()).hexdigest(),'obsoleteEvidencePaths':[k for k in base if k not in keep and k not in ['version','variants','mechanism','internalDrive','animation','animations','drivePhaseEncodingV22','assetEncoding','wingAttachmentReference']]}
manifest['variants']=copy.deepcopy(base['variants']);manifest['variants']['xp4'].update({'meshes':validation['meshInstances'],'triangles':validation['renderedTriangles'],'file':'xp4.glb'})
mechanism=copy.deepcopy(base['mechanism']);mechanism['version']=25;mechanism['sliderTravel']=[contract['actualTravel']['minimumY'],contract['actualTravel']['maximumY']];mechanism['persistentContract']=contract;mechanism['rootClearanceScope']='旧兼容轴向字段不是当前全局净距；当前主皮层隙与运动见本轮独立报告';mechanism['actualSlotTravelScope']='冻结基线槽孔及其原制作包络保持；本轮实际闭环行程见sliderTravel，不冒充改造了槽孔'
for side,sg in [('L',-1),('R',1)]:
 p=contract['actualRightPivot'];a=contract['wingAnchorRightCruise'];d=[sg*(a[0]-p[0]),a[1]-p[1],a[2]-p[2]];mechanism['sides'][side]['wingAnchorLocal']=[d[0],d[2],-d[1]];mechanism['sides'][side]['braceLength']=contract['rigidRodLength']
manifest['mechanism']=mechanism;manifest['internalDrive']=copy.deepcopy(base['internalDrive']);manifest['internalDrive']['stroke']=mechanism['sliderTravel'];manifest['internalDrive']['motionContractRevision']='2026-10-07-v25';manifest['internalDrive']['fixedLayoutAndStopGeometryPreserved']=True
manifest['wingAttachmentReference']={'source':'本轮新轴位下的定长连杆与原滑架行程闭合拟合','worldBlenderCruise':contract['wingAnchorRightCruise'],'fitIsIllustrative':True,'exactImagePixelRegistrationClaimed':False}
manifest['animation']=copy.deepcopy(base['animation']);manifest['animation']['description']='本轮重新烘焙的整翼、连杆、滑架与驱动轴动作；网页另使用同一机构参数驱动'
manifest['animations']=copy.deepcopy(base['animations']);manifest['animations'][0]['purpose']='本轮整翼新几何与定长闭环动作';manifest['drivePhaseEncodingV22']=doc['extras']['drivePhaseEncodingV22'];manifest['assetEncoding']=encoding
manifest['assets']={name:{'bytes':(STAGE/name).stat().st_size,'sha256':hashlib.sha256((STAGE/name).read_bytes()).hexdigest()}for name in ['xp4.blend','xp4-source.glb','xp4.glb']}
(STAGE/'model-manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print('WROTE',STAGE/'model-manifest.json')

cache_key="20261007-v25-"+hashlib.sha256((STAGE/"xp4.glb").read_bytes()).hexdigest()[:8]
(ROOT/"src/modelAssetRevision.ts").write_text('/** 内容版本是缓存键；同页视图切换复用同一 GLB。 */\nexport const MODEL_ASSET_REVISION = '+json.dumps(cache_key)+';\nexport function modelAssetUrl(variant: "xp4") {\n  return `/models/${variant}.glb?v=${MODEL_ASSET_REVISION}`;\n}\n')
